export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE'

export const CUSTOMER_REGISTER_REQUEST = 'CUSTOMER_REGISTER_REQUEST'
export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSTOMER_REGISTER_FAILURE = 'CUSTOMER_REGISTER_FAILURE'

export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST'
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS'
export const RESTAURANT_LOGIN_FAILURE = 'RESTAURANT_LOGIN_FAILURE'

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST'
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS'
export const RESTAURANT_REGISTER_FAILURE = 'RESTAURANT_REGISTER_FAILURE'